// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sumccdiomnefdknrtotl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1bWNjZGlvbW5lZmRrbnJ0b3RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNzg2MjYsImV4cCI6MjA2MTc1NDYyNn0.dNS4vcjLC-IgqoiB1WNlRnxls0wYbBI6yWETkxOj30Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);